### ISSUE TITLE
[Bug] 会员全文 RSS 在 Readwise Reader 中无法正常显示

### ISSUE THREAD

**Issue by yarin-zhang** [UntagTeam/Untag-Forum#12]
> 问题描述

用户反馈，反馈一个premium rss订阅源的问题
以《UNTAG Premium 第十七期》为例，inoreader
可以抓取到全文，但是readwise reader只能抓到目
录，不懂时什么原因导致的。

> 相关截图

![image](https://user-images.githubusercontent.com/58888890/222936876-b593cf3a-d168-43fd-966c-332cdfeb7e82.png)

**Comment by howie-chen** [comment]
遇到相同的问题，在 Readwise Reader 中无法抓取文章内容，而本地 Reeder 却可以，希望能够支持 Readwise Reader，谢谢！

<img width="1724" alt="image" src="https://github.com/UntagTeam/Untag-Forum/assets/8604973/d3dac34c-e151-40ec-be92-41a7b4274841">

<img width="1724" alt="image" src="https://github.com/UntagTeam/Untag-Forum/assets/8604973/6a31339b-7a5c-4f2c-b6a7-899502f78948">

**Comment by yarin-zhang** [comment]
更新一下此 Issue 的最新进展。

由于我们采用的是标准 RSS 协议，而且目前仅在 Readwise Reader 中发现此类反馈，其他阅读器（本地的、在线的）还没有出现过类似情况。这意味着我们没有办法在网站这一侧做任何改进。

所以我们向 Readwise Reader 做了反馈，他们刚刚回信表示”已向开发团队反馈“。具体的功能修复需要等待对方的回复。

**Comment by yarin-zhang** [comment]
经过与 Readwise Reader 开发团队的沟通，现在 Readwise Reader 可以正常处理 #UNTAG 的两种 RSS 订阅了，看起来效果不错：

会员 RSS 效果：

![image](https://github.com/UntagTeam/Untag-Forum/assets/58888890/9af9eb6e-a354-4000-ad2d-f6465a1ef7ac)

摘要 RSS 效果：

![image](https://github.com/UntagTeam/Untag-Forum/assets/58888890/a1a4081a-d657-47dc-9185-2d42e9398697)
