### ISSUE TITLE
[Bug]文章配图压缩的似乎有些太严重了，看起来有些包浆

### ISSUE THREAD

**Issue by erpwibw** [UntagTeam/Untag-Forum#16]
> 问题描述
文章配图压缩的似乎有些太严重了，看起来有些包浆

> 相关截图
![image](https://user-images.githubusercontent.com/23517447/224536106-ebc8c08a-04a2-43bc-95bd-6e88e2389e18.png)

> 使用环境
 - 浏览器： [例如：Chrome]

**Comment by yarin-zhang** [comment]
看上去是这张图片的问题，比如[同一篇文章](https://utgd.net/article/20105)中的其他图片似乎就是正常的：

![](https://cdn.utgd.net/assets/uploads/2022/00/minja-0302175149.jpeg)

其他文章也暂时没有发现这样的情况，目前图片都是原始尺寸上传，只在 CDN 进行过一次压缩，不应该出现这么严重的画质损失。我们会持续观察一下是否有类似情况出现。

**Comment by yarin-zhang** [comment]
暂时没有在新文章中发现此类问题，先关闭 Issue 了
