### ISSUE TITLE
[Bug] 作者详情页-最新文章显示顺序错误

### ISSUE THREAD

**Issue by yansq** [UntagTeam/Untag-Forum#17]
> 问题描述

在作者详情页，如[Hum](https://utgd.net/author/10031)的，“最新文章”的顺序是从旧到新，而“最新评论”的顺序是从新到旧，应该都统一为按时间倒序排列。

> 相关截图

<img width="1267" alt="CleanShot 2023-03-13 at 10 50 29@2x" src="https://user-images.githubusercontent.com/26108404/224597206-5235c146-ab4e-4da9-ab16-e90266c6660f.png">

> 使用环境
 - 设备： [MacbookPro]
 - 系统： [MacOS 13.2]
 - 浏览器： [Chrome]

**Comment by yarin-zhang** [comment]
这个问题已经得到解决
