### ISSUE TITLE
[Bug]点击脚注跳转时目标位置被顶部横幅遮挡

### ISSUE THREAD

**Issue by H-Tung** [UntagTeam/Untag-Forum#2]
### 问题描述：
目前脚注点击跳转时，目标位置位于页面顶端，会被顶部的导航横幅遮挡

### 截图：

![un](https://user-images.githubusercontent.com/67063101/192136810-9432b255-ddf8-439d-81cf-99b8a3cfc417.gif)

### 使用环境：
 - 设备： PC 
 - 系统： Windows 10
 - 浏览器： Vivaldi

### 其他补充：

我是认为跳转到页中比较好，但就算跳转到页顶也不该被挡住吧……

**Comment by yarin-zhang** [comment]
收到反馈，我们近期会进行改进~

**Comment by yarin-zhang** [comment]
我们近期做了一次重构更新，这个问题已经解决
