### ISSUE TITLE
[Bug]《Anki 进阶手册》购买过，但是提示“您还没有购买此教程，无法查看此教程的内容。”

### ISSUE THREAD

**Issue by VctN1** [UntagTeam/Untag-Forum#22]
《Anki 进阶手册》购买过，但是提示“您还没有购买此教程，无法查看此教程的内容。”

**Comment by yarin-zhang** [comment]
你好，麻烦给 service@tihushe.com 发送一下购买订单的订单号和购买截图（在网站头像 - 我的订单处截图即可），我们检查下问题出在哪里。后台没能直接搜到“VctN1”这个用户名下的订单。

目前有个已知问题是初次登录的时候如果已经在教程页面，可能会出现“您还没有购买此教程，无法查看此教程的内容。”这个提示，此时刷新一下页面就可以看到。这个问题我们会在近期解决。

**Comment by VctN1** [comment]
收到

**Comment by yarin-zhang** [comment]
已收到订单号截图，似乎是因为没有成功触发支付成功通知，导致后台没有更新订单状态导致的。总之是一个网站 Bug，我们会调查下原因。现已手动处理这笔订单。

**Comment by VctN1** [comment]
收到，已生效，感谢。
________________________________
发件人: hV极客 ***@***.***>
发送时间: 2023年5月4日 22:22
收件人: UntagTeam/Untag-Forum ***@***.***>
抄送: VctN1 ***@***.***>; Author ***@***.***>
主题: Re: [UntagTeam/Untag-Forum] [Bug]《Anki 进阶手册》购买过，但是提示“您还没有购买此教程，无法查看此教程的内容。” (Issue #22)


已收到订单号截图，似乎是因为没有成功触发支付成功通知，导致后台没有更新订单状态导致的。总之是一个网站 Bug，我们会调查下原因。现已手动处理这笔订单。

―
