### ISSUE TITLE
[Bug]搜索结果页面没有获取到教程信息

### ISSUE THREAD

**Issue by erpwibw** [UntagTeam/Untag-Forum#24]
> 问题描述
在 google 搜索“anki 教程”时，UNTAG 会出现在搜索结果的第 3 页，
但是搜索结果页面没有获取到教程信息，不能够提供有效参考。

> 相关截图
![image](https://user-images.githubusercontent.com/23517447/236388159-de134828-7601-4d9d-ab65-a29d5799a6dc.png)

> 使用环境

 
 

> 其他补充

**Comment by yarin-zhang** [comment]
收到，这个问题与 #25 类似，我们会尽快修改为正确的教程名称和产品名称。

**Comment by yarin-zhang** [comment]
改进教程名称和产品名称的功能已经完成，代码已经更新，应该能一定程度上解决此问题。Google 缓存需要一段时间才会更新。有待持续观察。

往深了说，这是一个目前网站架构的问题，现在是通过静态网页+异步请求获取内容的方式。这种方式的缺点是对 SEO 不太友好，搜索引擎不太容易抓到其中的内容，或者像这样只显示一个页面默认的标题。

我们正在想办法着手改进，方向也基本确定了，不过调整起来会比较花时间花精力，目前也还在做其他新功能，可能需要花一段时间才能彻底解决此问题。

我先关闭此 Issue，被转为内部 Issue 持续改进。
