### ISSUE TITLE
[Bug]教程的网页标题不能够跟随章节变化

### ISSUE THREAD

**Issue by erpwibw** [UntagTeam/Untag-Forum#25]
> 相关截图
![image](https://user-images.githubusercontent.com/23517447/236389007-b222e4d8-b740-4ba5-b0ec-1ea73423f789.png)

 
 

> 其他补充

**Comment by yarin-zhang** [comment]
收到，我们会跟进下这个问题。

**Comment by yarin-zhang** [comment]
这个问题已经解决。

现在“产品、教程、课时、分类、标签”这五类页面，都加入了动态标题显示。

<img width="450" alt="image" src="https://user-images.githubusercontent.com/58888890/236786166-4396df03-ed1c-410e-ab6e-8bdf70fec158.png">
