### ISSUE TITLE
[Bug] 文章目录中的文本过长时会与项目符号分离

### ISSUE THREAD

**Issue by jackzheng870** [UntagTeam/Untag-Forum#27]
> 问题描述

在文章的目录中，当目录标题太长需要两行显示时，其会整体换行，导致视觉上与前面的项目符号分离。

> 相关截图

![image](https://github.com/UntagTeam/Untag-Forum/assets/6195451/77c50b90-b569-449e-abcd-4d7ee9d0de0e)

> 使用环境
 - 设备：Mac Studio
 - 系统：macOS Ventura 13.4
 - 浏览器：Safari 16.5

> 其他补充

稍微研究了一下，看起来是 `flex-flow: wrap;` 导致了换行。我不确定移除这个属性会不会有什么负面影响，不过目前这样不太美观，如果能改进就最好了。以下是移除属性后的截图：

![image](https://github.com/UntagTeam/Untag-Forum/assets/6195451/269d5966-9013-490f-af3d-848cfd1b5578)

**Comment by yarin-zhang** [comment]
经过调查，是使用了一个错误组件导致的问题。

目前已经修复了，可以多刷新几次页面，查看最新效果。

<img width="311" alt="image" src="https://github.com/UntagTeam/Untag-Forum/assets/58888890/5cb8d244-eccc-4d9c-94ee-ba7173d13bff">

非常感谢反馈！
