### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VctN1** [UntagTeam/Untag-Forum#3]
问题描述：
- 网页加载有些慢
- 评论功能显示空白
- 关于《Anki 进阶手册/1-1 Anki 卡片结构》里，有两点疑惑想探讨一下：1. 原文“请试着调换一下图中的 {FrontSide} 和 Back”里，其中“back”外是否应有花括号？ 2. “{FrontSide}”外是否还应有一对花括号呢？因为软件里是“ {{FrontSide}}”。

截图：

使用环境：
 - 设备： [例如：iPhone 14]
 - 系统： [例如：iOS 16]
 - 浏览器： [例如：Chrome, Safari]

其他补充：

**Comment by yarin-zhang** [comment]
1. 网页加载问题我们已经在着手解决，不过工作量比较大，会花一点时间。在完成更新后会在 Slack 群第一时间通知大家。
2. 教程评论区确实有这个问题，应该是某次更新带来的问题，近期会做一下修复。
3. Minja 回复：这两个都有双花括号，应该是文章排版时代码块没有渲染出来。

**Comment by VctN1** [comment]
收到。问下，仅购买 Anki 课程的，能否加入Slack 群呢？
________________________________
发件人: yarin-zhang ***@***.***>
发送时间: 2022年10月7日 14:50
收件人: UntagTeam/Untag-Forum ***@***.***>
抄送: VctN1 ***@***.***>; Author ***@***.***>
主题: Re: [UntagTeam/Untag-Forum] [Bug] (Issue #3)


  1.  网页加载问题我们已经在着手解决，不过工作量比较大，会花一点时间。在完成更新后会在 Slack 群第一时间通知大家。
  2.  教程评论区确实有这个问题，应该是某次更新带来的问题，近期会做一下修复。
  3.  Minja 回复：这两个都有双花括号，应该是文章排版时代码块没有渲染出来。

―

**Comment by VctN1** [comment]
已在 Slack 群。请忽略上一条回复。
________________________________
发件人: yarin-zhang ***@***.***>
发送时间: 2022年10月7日 14:50
收件人: UntagTeam/Untag-Forum ***@***.***>
抄送: VctN1 ***@***.***>; Author ***@***.***>
主题: Re: [UntagTeam/Untag-Forum] [Bug] (Issue #3)


  1.  网页加载问题我们已经在着手解决，不过工作量比较大，会花一点时间。在完成更新后会在 Slack 群第一时间通知大家。
  2.  教程评论区确实有这个问题，应该是某次更新带来的问题，近期会做一下修复。
  3.  Minja 回复：这两个都有双花括号，应该是文章排版时代码块没有渲染出来。

―
