### ISSUE TITLE
[Bug] 教程中的文章无法进行评论

### ISSUE THREAD

**Issue by erpwibw** [UntagTeam/Untag-Forum#33]
> 问题描述
教程中的文章无法进行评论
https://utgd.net/course/20189/lesson/20202

> 相关截图

![image](https://github.com/UntagTeam/Untag-Forum/assets/23517447/8f115779-19e6-4b90-99cb-2eb9dd91d8e7)

> 使用环境

**Comment by yarin-zhang** [comment]
教程模块的相关功能会跟进开发，目前可以通过 Slack 群和作者交流。

[🔗 加入社群](https://utgd.net/community) `https://utgd.net/community`

**Comment by yarin-zhang** [comment]
此问题已解决，添加了点赞评论功能，并且修复了头像显示问题、目录显示问题。

![image](https://github.com/UntagTeam/Untag-Forum/assets/58888890/1c166ccd-d98e-44b7-ad63-797d0485d06e)
